#!/usr/bin/env php
<?php

set_time_limit(0);

$loader = require_once __DIR__.'/bootstrap.php.cache';

$app_loader = new AppLoader(__DIR__ . '/../app', $loader);

$input = new ArgvInput();

$app_loader->environment = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: $app_loader->environment);

if (getenv('SYMFONY_DEBUG') === '0') {
    $app_loader->debug = false;
} elseif ($input->hasParameterOption(array('--no-debug', ''))) {
    $app_loader->debug = true;
}

$app_loader->handleConsole($input);
