#!/usr/bin/env php
<?php

use WMC\AppLoader\AppLoader;
use Symfony\Component\Console\Input\ArgvInput;

$loader = require_once __DIR__.'/bootstrap.php.cache';

$app_loader = new AppLoader(__DIR__ . '/../app', $loader);
$app_loader->handleConsole(new ArgvInput());
